ensure certificate revocation list database exists (#45)
* workaround ansible issue "set_masquerade_enabled"

ERROR: Exception caught: set_masquerade_enabled() takes exactly 1 argument (6 given)"
https://github.com/ansible/ansible/pull/21693

* my fork not in ansible galaxy

* make sure crl database file exists

* Revert "my fork not in ansible galaxy"

This reverts commit af1d9c3a464934d8597ab6e4468c20a15161ee7c.